name: Deploy to Retinbox Web Hosting

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: shangzheny/rth-host-helper:latest

    steps:
      - name: Deploy to Retinbox Web Hosting
        uses: rthsoftware/host-auto-deploy@master
        env:
          RTH_API_KEY: ${{ secrets.RTH_API_KEY }}
        with:
          site: "mcjpg.org"  # 修改 example 为您的网站名称
          build: "viteprees build docs"  # 修改 build 为您的构建命令
          outdir: "docs"  # 修改 dist 为您的构建输出目录
